name: Node CI

on: [push]
env:
  FORCE_COLOR: 2
jobs:
  test:
    name: v${{ matrix.node }} @ ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node:
          - 8
          - 10
          - 12
          - 14
          - 16
          - 18
          - 20
          - 22
        os:
          - ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
        registry-url: 'https://registry.npmjs.org'
        cache: ''
    - run: npm config --global set spin false
      if: '${{ matrix.node < 18 }}'
    - run: yarn install --frozen-lockfile
    - run: yarn run test
